# Generated by Django 5.1.1 on 2024-11-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='registration',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.studentregistration'),
            preserve_default=False,
        ),
    ]
