# Generated by Django 5.1.1 on 2024-11-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_registrationperiod_description'),
        ('admission', '0002_payment_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.level'),
            preserve_default=False,
        ),
    ]
