# Generated by Django 5.1.1 on 2024-11-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_course_code'),
        ('admission', '0003_studentregistration_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='academic_year',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='academy.academicyear'),
        ),
    ]
