# Generated by Django 5.1.1 on 2024-10-31 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_department_options_alter_faculty_options_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprofile',
            name='faculty',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='academy.faculty'),
        ),
    ]
