# Generated by Django 5.1.1 on 2024-11-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_academicprofile_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academichistory',
            options={'ordering': ['-academic_year'], 'verbose_name_plural': 'Academic histories'},
        ),
    ]
