# Generated by Django 5.1.1 on 2024-11-03 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_registrationperiod_description'),
        ('profiles', '0003_alter_academichistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprofile',
            name='current_academy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.academichistory'),
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.department'),
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='faculty',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='academy.faculty'),
        ),
    ]
