# Generated by Django 5.1.1 on 2024-10-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
