# Generated by Django 5.1.1 on 2024-11-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_academicyear_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationperiod',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
