# Generated by Django 5.1.1 on 2024-11-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_registrationperiod_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
